---
- name: IP address calc
  hosts: localhost
  gather_facts: false
  vars:
    wanip: "{{WAN_SUBNET}}"
    lanip: "{{LAN_SUBNET}}"
    dia_wanip: "{{DIA_WAN_SUBNET}}"
    dia_lanip: "{{DIA_LAN_SUBNET}}"
  tasks:
  # Variable validation 
  - name: Verify MPLS WAN subnet
    assert:
      that:
       - "wanip | ipv4"
      fail_msg: "Incorrect WAN subnet provided"
      success_msg: "WAN subnet is valid"

  - name: Verify DIA WAN subnet
    assert:
      that:
       - "dia_wanip | ipv4"
      fail_msg: "Incorrect DIA WAN subnet provided"
      success_msg: "DIA WAN subnet is valid"
  - name: Verify MPLS LAN subnet
    assert:
      that:
       - "lanip | ipv4"
      fail_msg: "Incorrect LAN subnet provided"
      success_msg: "LAN subnet is valid"
  - name: Verify CPE LAN IP Address
    assert:
      that:
       - "LAN_IP_ADD | ipv4"
      fail_msg: "Incorrect LAN IP address provided"
      success_msg: "LAN IP is valid"

  - name: Verify DIA LAN subnet
    assert:
      that:
       - "dia_lanip | ipv4"
      fail_msg: "Incorrect DIA LAN subnet provided"
      success_msg: "DIA LAN subnet is valid"

  - name: define cpe mpls wan ip variable
    set_fact:
      cpeip: "{{ wanip | ipaddr('2') }}"

  - name: define cpe dia wan ip variable
    set_fact:
      dia_cpeip: "{{ dia_wanip | ipaddr('2') }}"
    
  - name: Validate primary backup variables
    # Accepted values are 0,1 and 2
    assert:
      that: 
       - PRIM_SEC <= 2
       - PRIM_SEC >= 0
      fail_msg: "Incorrect value"
      success_msg: "Value is correct"   
  - name: split mpls neitowrk
    set_fact:
      getcpeip: "{{ cpeip | ipaddr('address') }}"
  - name: print cpe wan ip variable
    debug:
      msg: "{{getcpeip}}"
  - name: define pe ip variable
    set_fact:
      peip: "{{ wanip | ipaddr('1') }}"
  - name: split netowrk
    set_fact:
      getpeip: "{{ peip | ipaddr('address') }}"
  - name: define cpe lan variables
    set_fact:
      cpelanip: "{{ LAN_SUBNET }}"
  - name: Split LAN Netowrk
    set_fact:
      getcpelanip: "{{ cpelanip | ipaddr('address') }}"
      getcpelanmask:  "{{ cpelanip | ipaddr('netmask') }}"
      getcpenetwork: "{{ cpelanip | ipaddr('network') }}"
      getcpwild: "{{ cpelanip | ipaddr('hostmask') }}"
  - name: Loop static route prefix list
    set_fact:
      statipnet: "{{ STATIC_PREFIX | ipaddr('network') }}"
      statipmask: "{{ STATIC_PREFIX | ipaddr('netmask') }}"
      statipwild: "{{ STATIC_PREFIX | ipaddr('hostmask') }}"
    loop:
      - "{{STATIC_PREFIX}}"
  - name: Split SSH allowed networks
    set_fact:
      sshnet: "{{ SSH_NETWORK_ALLOW | ipaddr('network') }}"
      sshwild: "{{ SSH_NETWORK_ALLOW | ipaddr('hostmask') }}"
    loop:
      - "{{SSH_NETWORK_ALLOW}}"
  - name: Custmer SNMP 
    set_fact:
      snmpnet: "{{ acl12 | ipaddr('network') }}"
      snmpwild: "{{ acl12 | ipaddr('hostmask') }}"
    loop:
      - "{{acl12}}" 
  - name: Customer Loopback 
    set_fact:
      loopbackip: "{{ LOOPBACK_IP | ipaddr('address') }}"
      loopbackmask: "{{ LOOPBACK_IP | ipaddr('netmask') }}"

  - name: split dia neitowrk
    set_fact:
      dia_getcpeip: "{{ dia_cpeip | ipaddr('address') }}"
  - name: print cpe dia wan ip variable
    debug:
      msg: "{{dia_getcpeip}}"
  - name: define dia pe ip variable
    set_fact:
      dia_peip: "{{ dia_wanip | ipaddr('1') }}"
  - name: split netowrk
    set_fact:
      dia_getpeip: "{{ dia_peip | ipaddr('address') }}"
  - name: print PE variable
    debug:
      var: dia_getpeip
  - name: Define CPE DIA LAN Variables
    set_fact:
      dia_cpelanip: "{{ dia_lanip | ipaddr('1') }}"
  - name: Split DIA LAN Netowrk
    set_fact:
      dia_getcpelanip: "{{ dia_cpelanip | ipaddr('address') }}"
      dia_getcpelanmask:  "{{ dia_cpelanip | ipaddr('netmask') }}"
      dia_getcpenetwork: "{{ dia_cpelanip | ipaddr('network') }}"
      dia_getcpwild: "{{ dia_cpelanip | ipaddr('hostmask') }}"

  - name: Create dummy host to transfer variables
    add_host:
      name: "DUMMY_HOST"
      ansible_host: "{{getcpeip}}"
      ansible_ipaddress: "{{getcpeip}}"
      ansible_user: admin
      gether_facts: False
      groups: dummygroup
      getcpewanip: "{{getcpeip}}"
      peip: "{{getpeip}}"
      lanip: "{{LAN_IP_ADD}}"
      lannet: "{{LAN_SUBNET}}"
      lanmask: "{{getcpelanmask}}"
      lansubnet: "{{getcpenetwork}}"
      wildcard: "{{getcpwild}}"
      hostname: "{{EQPT_SLID}}"
      cpestatipnet: "{{statipnet}}"
      cpestatipmask: "{{statipmask}}"
      cpestatipwild: "{{statipwild}}"
      SSHNET: "{{sshnet}}"
      SSHWILD: "{{sshwild}}"
      SNMPNET: "{{snmpnet}}"
      SNMPWILD: "{{snmpwild}}"
      loopbackip: "{{loopbackip}}"
      loopbackmask: "{{loopbackmask}}"
      dia_peip: "{{dia_getpeip}}"
      dia_cpelanip: "{{dia_getcpelanip}}"
      dia_lanmask: "{{dia_getcpelanmask}}"
      dia_lansubnet: "{{dia_getcpenetwork}}"
      dia_wildcard: "{{dia_getcpwild}}"

  - name: Run expect commands and delegate task to bastion host
    #async: 30
    #poll: 1
    ansible.builtin.shell: |
      set timeout 5
      spawn telnet "{{ hostvars['DUMMY_HOST']['getcpewanip'] }}"
      expect "Password:"
      send "cisco\n"
      expect "*>"
      send "enable\n"
      expect "Password:"
      send "cisco\n"
      expect "#"
      send "terminal length 0\n"
      expect "#"
      send "conf t\r"
      expect "(config)#"
      send "username admin password 0 cisco\n"
      expect "(config)#"
      send "ip domain name gtt.net\n"
      expect "(config)#"
      send "crypto key generate rsa\n"
      expect ":"
      send "2048\r"
      expect "(config)#"
      send "ip ssh version 2\r"
      expect "(config)#"
      send "aaa new-model\r"
      expect "*(config)#"
      send "aaa authentication login default local\r"
      expect "(config)#"
      send "end\n"
      expect "#"
      exit 0
    register: tclout
    args:
      executable: /usr/bin/expect
    delegate_to: bastion_host
  - name: get stdout
    debug:
      msg: "{{tclout}}"
  
- hosts: dummygroup
  gather_facts: False
  connection: network_cli
  roles:
   - { role: dia_mpls }
  vars:
    fname: "{{EQPT_SLID}}"
    pewanipaddr: "{{ hostvars['DUMMY_HOST']['peip'] }}"
    lanip: "{{ hostvars['DUMMY_HOST']['lanip'] }}"
    lanmask:  "{{ hostvars['DUMMY_HOST']['lanmask'] }}"
    lansubnet: "{{ hostvars['DUMMY_HOST']['lansubnet'] }}"
#
    dia_pewanipaddr: "{{ hostvars['DUMMY_HOST']['dia_peip'] }}"
    dia_cpelanip: "{{ hostvars['DUMMY_HOST']['dia_cpelanip'] }}"
    dia_lanmask:  "{{ hostvars['DUMMY_HOST']['dia_lanmask'] }}"
    dia_lansubnet: "{{ hostvars['DUMMY_HOST']['dia_lansubnet'] }}"    
  vars_files:
    - group_vars/routers.yml    
  tasks:
  - debug:
      msg: "CPE-{{ACRO}}-{{EQPT_SLID}} provision completed"
  - debug:
      msg: "cpeinit -t ssh -l admin -p cisco {{getcpewanip}}"
